name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest, macos-latest]
        example:
          - "examples/cmsis-blink"
          - "examples/sdk-blink"
          - "examples/sdk-uart-print"
          - "examples/sdk-ble-beacon"
          - "examples/sdk-ble-freertos-template"
          - "examples/sdk-mbedtls"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
          pio pkg install -g -t "https://github.com/maxgerhardt/pio-tool-goodix-gprogrammer.git#linux"
          ls -la ~/.platformio/packages/tool-goodix-gprogrammer
          ldd ~/.platformio/packages/tool-goodix-gprogrammer/GR5xxx_console
          ldd ~/.platformio/packages/tool-goodix-gprogrammer/libjlinkarm.so.6
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}